### PR TITLE
Order on motion to waive fees

### PR DESCRIPTION
**Pull request by Mengqi89**
Added a few changes to this branch to address 9, 10 and 15 in https://github.com/JustUtahCoders/utahexpungements.org/issues/183

### CODE REVIEW

**Comment by benschinn** [comment]
this PR addresses issues 9,10, and 15. but I did notice that respondent/defendant is not printing on the motion to waive fees form.

**Comment by oliviaclyde** [comment]
@benschinn I merged this. Should I revert allowing for more review?

**Comment by benschinn** [comment]
@oliviaclyde no, I don't think that's not necessary! I'll try and add a PR today to make sure defendant/respondent is printing in motion to waive fees form.

Also @Mengqi89 ur PR was great! it addresses everything in 9,10, and 15. just found something else that wasn't listed in the issues.

**Comment by Mengqi89** [comment]
> @oliviaclyde no, I don't think that's necessary! I'll try and add a PR today to make sure defendant/respondent is printing in motion to waive fees form.
> 
> Also @Mengqi89 ur PR was great! it addresses everything in 9,10, and 15. just found something else that wasn't listed in the issues.

I noticed that too. But seeing the field is missing in the web form, I did not include the data on the pdf output. Should we also add a form field in the web form?

**Pull request merged**
