### PR TITLE
Issue #176: Removed beta tester email field

### PR DESCRIPTION
**Pull request by nathan-gilbert**
Not sure this is what you want, but trying to help with some low hanging fruit.

### CODE REVIEW

**Comment by benschinn** [comment]
Hey @nathan-gilbert thanks for your help with addressing issue https://github.com/JustUtahCoders/utahexpungements.org/issues/176! Perhaps we should add a 'Sign Up' button here instead that takes you to the sign up form for non-authenticated state, and a 'welcome "user"' text if user is signed in?

cc: @lukeschunk

**Comment by lukeschunk** [comment]
hey that looks good to me. @nathan-gilbert can you take a quick screenshot of what the home screen looks like without that page. i think this should be fine though

**Review by lukeschunk — APPROVED** [review]

**Comment by lukeschunk** [comment]
merged and released; it looks good, no need for the screenshot

**Comment by nathan-gilbert** [comment]
Thanks, sorry wasn't able to reply sooner

**Pull request merged**
